namespace IonCrm.Domain.Enums;

/// <summary>
/// Payment type chosen for a customer subscription contract.
/// </summary>
public enum ContractPaymentType
{
    /// <summary>Credit card via iyzico recurring subscription (no auto-invoice).</summary>
    CreditCard = 0,

    /// <summary>EFT / Wire transfer — monthly draft invoice is auto-generated by background job.</summary>
    EftWire = 1
}
